import{n as d}from"./assets/vendor-BY9c7rfI.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const a={taskForm:document.querySelector(".task-form"),taskList:document.querySelector("#task-list"),deleteBtn:document.querySelector(".task-list-delete-btn")};function f({name:e,description:s,id:r}){const o=`<li class='task-list-item'>
    <h3 class="task-list-title">${e}</h3>
    <p class="task-list-description">${s}</p>
    <button class="task-list-delete-btn" data-id="${r}" type="button">Delete</button>
</li>`;a.taskList.insertAdjacentHTML("beforeend",o)}function u(e){const s=e.map(({name:r,description:o,id:t})=>`<li class='task-list-item'>
    <h3 class="task-list-title">${r}</h3>
    <p class="task-list-description">${o}</p>
    <button class="task-list-delete-btn" data-id="${t}" type="button">Delete</button>
</li>`).join("");a.taskList.innerHTML=s}const c={TASKS:"tasks",THEME:""};function i(){try{return JSON.parse(localStorage.getItem(c.TASKS))}catch{console.log("помилка читання тасок з localStorage")}}function m(){const e=i()??[];localStorage.setItem(c.TASKS,JSON.stringify(e))}function k(e){const s=i();s.push(e),localStorage.setItem(c.TASKS,JSON.stringify(s))}function p(e){const r=i().filter(o=>o.id!==e);localStorage.setItem(c.TASKS,JSON.stringify(r))}function S(e){e.preventDefault();const{taskName:s,taskDescription:r}=e.target.elements,o=s.value.trim(),t=r.value.trim();if(!o||!t){alert("!!!!!!!!!!!!!!");return}const n={name:o,description:t,id:d()};f(n),k(n),e.target.reset()}function g(e){m();const s=i();u(s)}function y(e){if(e.target.nodeName!=="BUTTON")return;const s=e.target.dataset.id;p(s);const r=i();u(r)}document.addEventListener("DOMContentLoaded",g);a.taskForm.addEventListener("submit",S);a.taskList.addEventListener("click",y);
//# sourceMappingURL=index.js.map
